;fAVOURITE HEADER SECTION
;--------------------------------------------

TMR0	EQU	1
ZEROBIT	EQU	2
STATUS	EQU	3
PORTA	EQU	5
PORTB	EQU	6
TRISA	EQU	85H
TRISB	EQU	86H
OPTION_R EQU	81H
COUNT	EQU	0CH
ORG	0
PCL 	EQU	2
LIST P=16f84a

GOTO 	START
;CONFIG
;--------------------------------------------


__CONFIG H'3FF0'


;SUBROTINE
;--------------------------------------------

DELAY5	CLRF	TMR0
LOOPA	MOVF	TMR0,W
		SUBLW	.8
		BTFSS	STATUS,ZEROBIT
		GOTO	LOOPA
		RETLW	0

CONVERT		ADDWF	PCL
			RETLW	B'00001000'
			RETLW	B'00000001'
			RETLW	B'00000010'
			RETLW	B'00000100'
			RETLW	B'00001000'


;--------------------------------------------
; CONFIGURATION

START	BSF	STATUS,5
		MOVLW	B'00011111'
		MOVWF	TRISA

		MOVLW	B'00000000'
		MOVWF	TRISB
		
		MOVLW	B'00000111'
		MOVWF	OPTION_R

		BCF	STATUS,5
		CLRF	PORTA
		CLRF	PORTB

;--------------------------------------------
; BEGIN

BEGIN	CLRF	COUNT
PRESS	BTFSC	PORTA,0
		GOTO	PRESS
		CALL	DELAY5
		INCF	COUNT
		MOVF	COUNT,W
		SUBLW	.4
		BTFSC	STATUS,ZEROBIT
		CLRF	COUNT
		MOVF	COUNT,W
		CALL	CONVERT
		MOVWF	PORTB
		
RELEASE	BTFSS	PORTA,0
		GOTO	RELEASE
		GOTO	PRESS


END
